name: pull-request-build

on:
  pull_request:

permissions:
  contents: read

jobs:
  define-package-matrix:
    uses: ./.github/workflows/define-package-matrix.yml

  build-packages:
    needs: define-package-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.define-package-matrix.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    name: build ${{ matrix.name }} (${{ matrix.system }})
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build package
        run: nix build --print-build-logs .#packages.${{ matrix.system }}.${{ matrix.name }}
